name: Deploy Workflow
run-name: ${{github.actor}} started deployment to server

on:
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ercolani

        steps:
            - name: ssh connection
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOSTNAME }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PW }}
                script: whoami
      

            - name: checkout
              uses: actions/checkout@v4
