name: Checks mergeability of commits pushed and PRs
run-name: CI workflow run by ${{github.actor}}
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    ci:
        runs-on: ubuntu-latest
        outputs:
            package:
        steps:
            - uses: actions/checkout@v4 
            - uses: actions/setup-node@v4
              with:
                node-version: 
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test
            - uses: actions/upload-artifact@v4
              with:
                path: .
    deploy:
        runs-on: ubuntu-latest
        needs: ci
        environment: ercolani
        steps:
            - name: ssh connection
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOSTNAME }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PW }}
                script: whoami
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        needs: ci
        env:
            REGISTRY: ghcr.io
        steps:
            - uses: actions/download-artifact@v4
            - uses: docker/login-action@v3.1.0
              with:
                username: ${{github.actor}}
                password: ${{github.token}}
            - uses: docker/metadata-action@v5
              id: meta
              with:
                images: ${{env.REGISTRY}}/${{github.repository}}
            - uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{steps.meta.outputs.tags}}
                labels: ${{steps.meta.outputs.labels}}

